const translations = {
    th: {
        'greeting.morning': 'สวัสดีตอนเช้า',
        'greeting.noon': 'สวัสดีตอนเที่ยง',
        'greeting.afternoon': 'สวัสดีตอนบ่าย',
        'greeting.evening': 'สวัสดีตอนเย็น',
        'greeting.night': 'ราตรีสวัสดิ์',
        'step1.title': 'เลือกบริการ',
        'step1.button': 'ถัดไป',
        'step2.dateLabel': 'เลือกวันที่',
        'step2.timeLabel': 'เลือกเวลา',
        'step2.placeholder': 'ยังไม่ได้เลือกวัน',
        'step2.loading': 'โปรดรอสักครู่...',
        'step2.error': 'ไม่สามารถโหลดเวลาได้',
        'step2.noTime': 'ไม่มีช่วงเวลาว่าง',
        'step2.back': 'ย้อนกลับ',
        'step2.next': 'ถัดไป',
        'step3.title': 'ข้อมูลติดต่อ',
        'step3.firstNamePlaceholder': 'ชื่อจริง',
        'step3.lastNamePlaceholder': 'นามสกุล',
        'step3.phonePlaceholder': 'เบอร์ติดต่อ',
        'step3.idCardOrSocialPlaceholder': 'เลขที่บัตรประชาชน/เลขที่ประกันสังคม',
        'step3.diseaseAllergyPlaceholder': 'โรคประจำตัว/อาการแพ้ (ถ้ามี)',
        'step3.notePlaceholder': 'หมายเหตุ (ถ้ามี)',
        'step3.back': 'ย้อนกลับ',
        'step3.next': 'ถัดไป',
        'step4.title': 'ตรวจสอบข้อมูล',
        'step4.serviceLabel': 'บริการ:',
        'step4.dateLabel': 'วันที่:',
        'step4.timeLabel': 'เวลา:',
        'step4.nameLabel': 'ชื่อ-นามสกุล:',
        'step4.phoneLabel': 'เบอร์:',
        'step4.idCardOrSocialLabel': 'เลขบัตร/ประกัน:',
        'step4.diseaseAllergyLabel': 'โรค/แพ้:',
        'step4.noteLabel': 'หมายเหตุ:',
        'step4.back': 'ย้อนกลับ',
        'step4.confirm': 'ยืนยันการจอง',
        'popup.close': 'ปิด',
        'popup.calendarError': 'ไม่สามารถโหลดปฏิทินได้',
        'popup.serviceError': 'ไม่สามารถโหลดบริการได้',
        'popup.timeError': 'ไม่สามารถโหลดเวลาได้',
        'popup.serviceNeeded': 'กรุณาเลือกบริการอย่างน้อย 1 รายการ',
        'popup.dateNeeded': 'กรุณาเลือกวันที่',
        'popup.timeNeeded': 'กรุณาเลือกเวลา',
        'popup.firstNameNeeded': 'กรุณากรอกชื่อจริง',
        'popup.lastNameNeeded': 'กรุณากรอกนามสกุล',
        'popup.idCardOrSocialNeeded': 'กรุณากรอกเลขที่บัตรประชาชน/เลขที่ประกันสังคม',
        'popup.phoneNeeded': 'กรุณากรอกเบอร์ติดต่อ',
        'popup.phoneFormatError': 'รูปแบบเบอร์ติดต่อไม่ถูกต้อง',
        'popup.submitError': 'ส่งข้อมูลไม่สำเร็จ',
        'popup.bookingSuccess': 'การจองสำเร็จแล้ว!',
        'calendar.holiday': 'หยุด',
        'service.noService': 'ไม่พบรายการบริการ',
        // Service translations - Dental Services
        'service.ขูดหินปูน': 'ขูดหินปูน',
        'service.ตรวจฟัน': 'ตรวจฟันทั่วไป',
        'service.อุดฟัน': 'อุดฟัน',
        'service.ถอนฟัน': 'ถอนฟัน',
        'service.รักษารากฟัน': 'รักษารากฟัน',
        'service.ทำฟันปลอม': 'ทำฟันปลอม',
        'service.จัดฟัน': 'จัดฟัน',
        'service.ฟอกสีฟัน': 'ฟอกสีฟัน',
        'service.ครอบฟัน': 'ครอบฟัน/วีเนียร์',
        'service.ศัลยกรรมช่องปาก': 'ศัลยกรรมช่องปาก',
        'service.ทำความสะอาดฟัน': 'ทำความสะอาดฟัน',
        'service.รอยยิ้มใหม่': 'ออกแบบรอยยิ้มใหม่',
        'flex.header': 'ยืนยันการจองสำเร็จ',
        'flex.altText': 'รายละเอียดการจองของคุณ',
        'flex.serviceLabel': 'บริการ',
        'flex.dateLabel': 'วันที่',
        'flex.timeLabel': 'เวลา',
        'flex.nameLabel': 'ชื่อ',
        'flex.phoneLabel': 'เบอร์',
    'flex.noteLabel': 'หมายเหตุ',
    // --- History page ---
    'history.title': 'รายการนัดหมายของคุณ',
    'history.loading': 'กำลังโหลดข้อมูล...',
    'history.nodata': 'ไม่พบข้อมูล',
    'history.col.name': 'ชื่อ-นามสกุล',
    'history.col.date': 'วันที่',
    'history.col.status': 'สถานะ',
    'history.col.view': 'ดู',
    'history.status.all': 'ทั้งหมด',
    'history.status.pending': 'รอการยืนยัน',
    'history.status.confirmed': 'ยืนยันแล้ว',
    'history.status.cancelled': 'ยกเลิก',
    'history.status.completed': 'เสร็จสิ้น',
    'history.sort.latest': 'วันที่ล่าสุด',
    'history.sort.oldest': 'วันที่เก่าสุด',
    'history.view': 'ดู',
    'history.detail.name': 'ชื่อ:',
    'history.detail.phone': 'เบอร์โทร:',
    'history.detail.id': 'เลขบัตร/ประกัน:',
    'history.detail.disease': 'โรค/แพ้:',
    'history.detail.service': 'บริการ:',
    'history.detail.date': 'วันที่:',
    'history.detail.time': 'เวลา:',
    'history.detail.note': 'หมายเหตุ:',
    'history.detail.status': 'สถานะ:',
    'history.confirm': 'ยืนยัน',
    'history.cancel': 'ยกเลิก',
    'history.confirmQ': 'ยืนยันรายการนี้?',
    'history.cancelQ': 'ยกเลิกรายการนี้?',
    'history.success': 'ดำเนินการสำเร็จ',
    'history.error': 'เกิดข้อผิดพลาด',
    'confirm.title': 'จัดการนัดหมาย',
    'confirm.success': 'สำเร็จ!',
    'confirm.error': 'เกิดข้อผิดพลาด',
    'confirm.loading': 'กำลังดำเนินการ...',
    'confirm.resultSuccess': 'ดำเนินการเรียบร้อยแล้ว',
    'confirm.resultConfirm': 'ยืนยันการนัดหมายสำเร็จแล้ว',
    'confirm.resultCancel': 'ยกเลิกการนัดหมายสำเร็จแล้ว',
    'confirm.btn.confirm': 'ยืนยันนัดหมาย',
    'confirm.btn.cancel': 'ยกเลิก',
    'confirm.btn.close': 'ปิด',
    'confirm.label.name': 'ชื่อผู้จอง:',
    'confirm.label.service': 'บริการ:',
    'confirm.label.price': 'ราคา:',
    'confirm.label.date': 'วันที่:',
    'confirm.label.time': 'เวลา:'
    },
    en: {
        'greeting.morning': 'Good morning',
        'greeting.noon': 'Good day',
        'greeting.afternoon': 'Good afternoon',
        'greeting.evening': 'Good evening',
        'greeting.night': 'Good night',
        'step1.title': 'Select Service',
        'step1.button': 'Next',
        'step2.dateLabel': 'Select Date',
        'step2.timeLabel': 'Select Time',
        'step2.placeholder': 'No date selected',
        'step2.loading': 'Please wait...',
        'step2.error': 'Failed to load times',
        'step2.noTime': 'No available slots',
        'step2.back': 'Back',
        'step2.next': 'Next',
        'step3.title': 'Contact Information',
        'step3.firstNamePlaceholder': 'First Name',
        'step3.lastNamePlaceholder': 'Last Name',
        'step3.phonePlaceholder': 'Phone Number',
        'step3.idCardOrSocialPlaceholder': 'National ID/Social Security Number',
        'step3.diseaseAllergyPlaceholder': 'Disease/Allergy (optional)',
        'step3.notePlaceholder': 'Notes (optional)',
        'step3.back': 'Back',
        'step3.next': 'Next',
        'step4.title': 'Review Booking',
        'step4.serviceLabel': 'Service:',
        'step4.dateLabel': 'Date:',
        'step4.timeLabel': 'Time:',
        'step4.nameLabel': 'Full Name:',
        'step4.phoneLabel': 'Phone:',
        'step4.idCardOrSocialLabel': 'ID/Social Security:',
        'step4.diseaseAllergyLabel': 'Disease/Allergy:',
        'step4.noteLabel': 'Note:',
        'step4.back': 'Back',
        'step4.confirm': 'Confirm Booking',
        'popup.close': 'Close',
        'popup.calendarError': 'Failed to load calendar.',
        'popup.serviceError': 'Failed to load services.',
        'popup.timeError': 'Failed to load available times.',
        'popup.serviceNeeded': 'Please select at least one service.',
        'popup.dateNeeded': 'Please select a date.',
        'popup.timeNeeded': 'Please select a time.',
        'popup.firstNameNeeded': 'Please enter your first name.',
        'popup.lastNameNeeded': 'Please enter your last name.',
        'popup.idCardOrSocialNeeded': 'Please enter your ID/Social Security number.',
        'popup.phoneNeeded': 'Please enter your phone number.',
        'popup.phoneFormatError': 'Invalid phone number format.',
        'popup.submitError': 'Booking submission failed.',
        'popup.bookingSuccess': 'Booking successful!',
        'calendar.holiday': 'Holiday',
        'service.noService': 'No services found',
        // Service translations - Dental Services
        'service.ขูดหินปูน': 'Scaling & Polishing',
        'service.ตรวจฟัน': 'General Check-up',
        'service.อุดฟัน': 'Dental Filling',
        'service.ถอนฟัน': 'Tooth Extraction',
        'service.รักษารากฟัน': 'Root Canal Treatment',
        'service.ทำฟันปลอม': 'Dentures',
        'service.จัดฟัน': 'Orthodontics/Braces',
        'service.ฟอกสีฟัน': 'Teeth Whitening',
        'service.ครอบฟัน': 'Crown/Veneer',
        'service.ศัลยกรรมช่องปาก': 'Oral Surgery',
        'service.ทำความสะอาดฟัน': 'Dental Cleaning',
        'service.รอยยิ้มใหม่': 'Smile Makeover',
        'flex.header': 'Booking Confirmed',
        'flex.altText': 'Your booking details',
        'flex.serviceLabel': 'Service',
        'flex.dateLabel': 'Date',
        'flex.timeLabel': 'Time',
        'flex.nameLabel': 'Name',
        'flex.phoneLabel': 'Phone',
    'flex.noteLabel': 'Note',
    // --- History page ---
    'history.title': 'Your Appointments',
    'history.loading': 'Loading data...',
    'history.nodata': 'No data found',
    'history.col.name': 'Name',
    'history.col.date': 'Date',
    'history.col.status': 'Status',
    'history.col.view': 'View',
    'history.status.all': 'All',
    'history.status.pending': 'Pending',
    'history.status.confirmed': 'Confirmed',
    'history.status.cancelled': 'Cancelled',
    'history.status.completed': 'Completed',
    'history.sort.latest': 'Latest Date',
    'history.sort.oldest': 'Oldest Date',
    'history.view': 'View',
    'history.detail.name': 'Name:',
    'history.detail.phone': 'Phone:',
    'history.detail.id': 'ID/Social:',
    'history.detail.disease': 'Disease/Allergy:',
    'history.detail.service': 'Service:',
    'history.detail.date': 'Date:',
    'history.detail.time': 'Time:',
    'history.detail.note': 'Note:',
    'history.detail.status': 'Status:',
    'history.confirm': 'Confirm',
    'history.cancel': 'Cancel',
    'history.confirmQ': 'Confirm this item?',
    'history.cancelQ': 'Cancel this item?',
    'history.success': 'Operation successful',
    'history.error': 'Error occurred',
    'confirm.title': 'Manage Appointment',
    'confirm.success': 'Success!',
    'confirm.error': 'Error',
    'confirm.loading': 'Processing...',
    'confirm.resultSuccess': 'Operation completed',
    'confirm.resultConfirm': 'Appointment confirmed',
    'confirm.resultCancel': 'Appointment cancelled',
    'confirm.btn.confirm': 'Confirm',
    'confirm.btn.cancel': 'Cancel',
    'confirm.btn.close': 'Close',
    'confirm.label.name': 'Name:',
    'confirm.label.service': 'Service:',
    'confirm.label.price': 'Price:',
    'confirm.label.date': 'Date:',
    'confirm.label.time': 'Time:'
    },
    my: {
        'greeting.morning': 'မင်္ဂလာနံနက်ခင်းပါ',
        'greeting.noon': 'မင်္ဂလာနေ့လည်ခင်းပါ',
        'greeting.afternoon': 'မင်္ဂလာနေ့လည်ခင်းပါ',
        'greeting.evening': 'မင်္ဂလာညနေခင်းပါ',
        'greeting.night': 'ကောင်းသောညပါ',
        'step1.title': 'ဝန်ဆောင်မှုရွေးချယ်ပါ',
        'step1.button': 'ရှေ့သို့',
        'step2.dateLabel': 'နေ့ရက်ရွေးချယ်ပါ',
        'step2.timeLabel': 'အချိန်ရွေးချယ်ပါ',
        'step2.placeholder': 'နေ့ရက်မရွေးချယ်ရသေးပါ',
        'step2.loading': 'ခဏစောင့်ပေးပါ...',
        'step2.error': 'အချိန်တင်မရနိုင်ပါ',
        'step2.noTime': 'အချိန်မရှိပါ',
        'step2.back': 'နောက်သို့',
        'step2.next': 'ရှေ့သို့',
        'step3.title': 'ဆက်သွယ်ရန်အချက်အလက်',
        'step3.firstNamePlaceholder': 'နာမည်',
        'step3.lastNamePlaceholder': 'အမျိုးအမည်',
        'step3.phonePlaceholder': 'ဖုန်းနံပါတ်',
        'step3.idCardOrSocialPlaceholder': 'နိုင်ငံသား/လူမှုဖူလုံရေးနံပါတ်',
        'step3.diseaseAllergyPlaceholder': 'ရောဂါ/အာဟာရမတည့်မှု (ရှိပါက)',
        'step3.notePlaceholder': 'မှတ်ချက် (ရှိပါက)',
        'step3.back': 'နောက်သို့',
        'step3.next': 'ရှေ့သို့',
        'step4.title': 'အချက်အလက်ပြန်စစ်ပါ',
        'step4.serviceLabel': 'ဝန်ဆောင်မှု:',
        'step4.dateLabel': 'နေ့ရက်:',
        'step4.timeLabel': 'အချိန်:',
        'step4.nameLabel': 'နာမည်-အမျိုးအမည်:',
        'step4.phoneLabel': 'ဖုန်းနံပါတ်:',
        'step4.idCardOrSocialLabel': 'ID/လူမှုဖူလုံရေး:',
        'step4.diseaseAllergyLabel': 'ရောဂါ/အာဟာရမတည့်မှု:',
        'step4.noteLabel': 'မှတ်ချက်:',
        'step4.back': 'နောက်သို့',
        'step4.confirm': 'အတည်ပြုရန်',
        'popup.close': 'ပိတ်မည်',
        'popup.calendarError': 'ပြက္ခဒိန်တင်မရနိုင်ပါ',
        'popup.serviceError': 'ဝန်ဆောင်မှုတင်မရနိုင်ပါ',
        'popup.timeError': 'ရရှိနိုင်သောအချိန်တင်မရနိုင်ပါ',
        'popup.serviceNeeded': 'အနည်းဆုံးဝန်ဆောင်မှုတစ်ခုရွေးချယ်ပါ',
        'popup.dateNeeded': 'နေ့ရက်ရွေးချယ်ပါ',
        'popup.timeNeeded': 'အချိန်ရွေးချယ်ပါ',
        'popup.firstNameNeeded': 'ကျေးဇူးပြု၍ နာမည်ထည့်ပါ',
        'popup.lastNameNeeded': 'ကျေးဇူးပြု၍ အမျိုးအမည်ထည့်ပါ',
        'popup.idCardOrSocialNeeded': 'ကျေးဇူးပြု၍ ID/လူမှုဖူလုံရေးနံပါတ်ထည့်ပါ',
        'popup.phoneNeeded': 'ကျေးဇူးပြု၍ ဖုန်းနံပါတ်ထည့်ပါ',
        'popup.phoneFormatError': 'ဖုန်းနံပါတ်ပုံစံမမှန်ကန်ပါ',
        'popup.submitError': 'တင်ပြမှုမအောင်မြင်ပါ',
        'popup.bookingSuccess': 'ဘိုကင်အောင်မြင်ပါပြီ!',
        'calendar.holiday': 'အားလပ်ရက်',
        'service.noService': 'ဝန်ဆောင်မှုမရှိပါ',
        // Service translations - Dental Services
        'service.ขูดหินปูน': 'သွားကျောက်ရှင်းလင်းခြင်း',
        'service.ตรวจฟัน': 'သွားစစ်ဆေးခြင်း',
        'service.อุดฟัน': 'သွားဖောက်ခြင်း',
        'service.ถอนฟัน': 'သွားနုတ်ခြင်း',
        'service.รักษารากฟัน': 'သွားအမြစ်ကုသခြင်း',
        'service.ทำฟันปลอม': 'သွားတုလုပ်ခြင်း',
        'service.จัดฟัน': 'သွားညှိခြင်း',
        'service.ฟอกสีฟัน': 'သွားဖြူခြင်း',
        'service.ครอบฟัน': 'သွားဖုံးအုပ်ခြင်း',
        'service.ศัลยกรรมช่องปาก': 'ခံတွင်းခွဲစိတ်ကုသခြင်း',
        'service.ทำความสะอาดฟัน': 'သွားသန့်ရှင်းခြင်း',
        'service.รอยยิ้มใหม่': 'ပြုံးရွှင်မှုအသစ်ဒီဇိုင်း',
        'flex.header': '📋 ကြိုတင်မှာယူမှု အသေးစိတ်',
        'flex.altText': 'သင်၏ဘိုကင်အသေးစိတ်',
        'flex.serviceLabel': 'ဝန်ဆောင်မှု',
        'flex.dateLabel': 'နေ့ရက်',
        'flex.timeLabel': 'အချိန်',
        'flex.nameLabel': 'အမည်',
        'flex.phoneLabel': 'ဖုန်းနံပါတ်',
    'flex.noteLabel': 'မှတ်ချက်',
    // --- History page ---
    'history.title': 'သင့်ရဲ့ချိန်းဆိုမှုများ',
    'history.loading': 'ဒေတာတင်နေသည်...',
    'history.nodata': 'ဒေတာမရှိပါ',
    'history.col.name': 'အမည်',
    'history.col.date': 'ရက်စွဲ',
    'history.col.status': 'အခြေအနေ',
    'history.col.view': 'ကြည့်ရန်',
    'history.status.all': 'အားလုံး',
    'history.status.pending': 'စောင့်ဆိုင်းနေသည်',
    'history.status.confirmed': 'အတည်ပြုပြီး',
    'history.status.cancelled': 'ဖျက်သိမ်းပြီး',
    'history.status.completed': 'ပြီးဆုံးသည်',
    'history.sort.latest': 'နောက်ဆုံးရက်',
    'history.sort.oldest': 'အဟောင်းဆုံးရက်',
    'history.view': 'ကြည့်ရန်',
    'history.detail.name': 'အမည်:',
    'history.detail.phone': 'ဖုန်း:',
    'history.detail.id': 'ID/လူမှု:',
    'history.detail.disease': 'ရောဂါ/မတည့်မှု:',
    'history.detail.service': 'ဝန်ဆောင်မှု:',
    'history.detail.date': 'ရက်စွဲ:',
    'history.detail.time': 'အချိန်:',
    'history.detail.note': 'မှတ်ချက်:',
    'history.detail.status': 'အခြေအနေ:',
    'history.confirm': 'အတည်ပြုပါ',
    'history.cancel': 'ဖျက်ပါ',
    'history.confirmQ': 'ဤအချက်အလက်ကိုအတည်ပြုမည်လား?',
    'history.cancelQ': 'ဤအချက်အလက်ကိုဖျက်မည်လား?',
    'history.success': 'အောင်မြင်ပါသည်',
    'history.error': 'အမှားအယွင်း',

    },
    // --- Lao (lo) ---
    lo: {
        'greeting.morning': 'ສະບາຍດີເຊົ້າ',
        'greeting.noon': 'ສະບາຍດີຕອນທ່ຽງ',
        'greeting.afternoon': 'ສະບາຍດີຕອນບ່າຍ',
        'greeting.evening': 'ສະບາຍດີຕອນແລງ',
        'greeting.night': 'ຝັນດີ',
        // ... (other keys as needed)
        // --- History page ---
        'history.title': 'ປະຫວັດການນັດຫມາຍຂອງທ່ານ',
        'history.loading': 'ກຳລັງໂຫຼດຂໍ້ມູນ...',
        'history.nodata': 'ບໍ່ພົບຂໍ້ມູນ',
        'history.col.name': 'ຊື່',
        'history.col.date': 'ວັນທີ',
        'history.col.status': 'ສະຖານະ',
        'history.col.view': 'ເບິ່ງ',
        'history.status.all': 'ທັງໝົດ',
        'history.status.pending': 'ລໍຖ້າຢືນຢັນ',
        'history.status.confirmed': 'ຢືນຢັນແລ້ວ',
        'history.status.cancelled': 'ຍົກເລີກ',
        'history.status.completed': 'ສຳເລັດ',
        'history.sort.latest': 'ວັນທີໃໝ່ສຸດ',
        'history.sort.oldest': 'ວັນທີເກົ່າສຸດ',
        'history.view': 'ເບິ່ງ',
        'history.detail.name': 'ຊື່:',
        'history.detail.phone': 'ເບີໂທ:',
        'history.detail.id': 'ເລກບັດ/ປະກັນ:',
        'history.detail.disease': 'ໂຣກ/ແພ້:',
        'history.detail.service': 'ບໍລິການ:',
        'history.detail.date': 'ວັນທີ:',
        'history.detail.time': 'ເວລາ:',
        'history.detail.note': 'ໝາຍເຫດ:',
        'history.detail.status': 'ສະຖານະ:',
        'history.confirm': 'ຢືນຢັນ',
        'history.cancel': 'ຍົກເລີກ',
        'history.confirmQ': 'ຢືນຢັນລາຍການນີ້ບໍ?',
        'history.cancelQ': 'ຍົກເລີກລາຍການນີ້ບໍ?',
        'history.success': 'ດຳເນີນການສຳເລັດ',
        'history.error': 'ມີຂໍ້ຜິດພາດ',
    'confirm.title': 'ချိန်းဆိုမှုစီမံခြင်း',
    'confirm.success': 'အောင်မြင်သည်!',
    'confirm.error': 'အမှား',
    'confirm.loading': 'လုပ်ဆောင်နေသည်...',
    'confirm.resultSuccess': 'လုပ်ဆောင်မှုပြီးပါပြီ',
    'confirm.resultConfirm': 'ချိန်းဆိုမှုအတည်ပြုပြီးပါပြီ',
    'confirm.resultCancel': 'ချိန်းဆိုမှုဖျက်ပြီးပါပြီ',
    'confirm.btn.confirm': 'အတည်ပြုပါ',
    'confirm.btn.cancel': 'ဖျက်ပါ',
    'confirm.btn.close': 'ပိတ်ပါ',
    'confirm.label.name': 'အမည်:',
    'confirm.label.service': 'ဝန်ဆောင်မှု:',
    'confirm.label.price': 'စျေးနှုန်း:',
    'confirm.label.date': 'ရက်စွဲ:',
    'confirm.label.time': 'အချိန်:'
    }
};