const translations = {
    th: {
        'step1.title': 'เลือกบริการ',
        'step1.button': 'ถัดไป',
        'step2.dateLabel': 'เลือกวันที่',
        'step2.timeLabel': 'เลือกเวลา',
        'step2.placeholder': 'ยังไม่ได้เลือกวัน',
        'step2.loading': 'โปรดรอสักครู่...',
        'step2.error': 'ไม่สามารถโหลดเวลาได้',
        'step2.noTime': 'ไม่มีช่วงเวลาว่าง',
        'step2.back': 'ย้อนกลับ',
        'step2.next': 'ถัดไป',
        'step3.title': 'ข้อมูลติดต่อ',
        'step3.namePlaceholder': 'ชื่อ-สกุล',
        'step3.phonePlaceholder': 'เบอร์ติดต่อ',
        'step3.notePlaceholder': 'หมายเหตุ (ถ้ามี)',
        'step3.back': 'ย้อนกลับ',
        'step3.next': 'ถัดไป',
        'step4.title': 'ตรวจสอบข้อมูล',
        'step4.serviceLabel': 'บริการ:',
        'step4.dateLabel': 'วันที่:',
        'step4.timeLabel': 'เวลา:',
        'step4.nameLabel': 'ชื่อ:',
        'step4.phoneLabel': 'เบอร์:',
        'step4.noteLabel': 'หมายเหตุ:',
        'step4.back': 'ย้อนกลับ',
        'step4.confirm': 'ยืนยันการจอง',
        'popup.close': 'ปิด',
        'popup.calendarError': 'ไม่สามารถโหลดปฏิทินได้',
        'popup.serviceError': 'ไม่สามารถโหลดบริการได้',
        'popup.timeError': 'ไม่สามารถโหลดเวลาได้',
        'popup.serviceNeeded': 'กรุณาเลือกบริการอย่างน้อย 1 รายการ',
        'popup.dateNeeded': 'กรุณาเลือกวันที่',
        'popup.timeNeeded': 'กรุณาเลือกเวลา',
        'popup.nameNeeded': 'กรุณากรอกชื่อ-สกุล',
        'popup.phoneNeeded': 'กรุณากรอกเบอร์ติดต่อ',
        'popup.phoneFormatError': 'รูปแบบเบอร์ติดต่อไม่ถูกต้อง',
        'popup.submitError': 'ส่งข้อมูลไม่สำเร็จ',
        'popup.bookingSuccess': 'การจองสำเร็จแล้ว!',
        'calendar.holiday': 'หยุด',
        'service.noService': 'ไม่พบรายการบริการ',
        'flex.header': 'ยืนยันการจองสำเร็จ',
        'flex.altText': 'รายละเอียดการจองของคุณ',
        'flex.serviceLabel': 'บริการ',
        'flex.dateLabel': 'วันที่',
        'flex.timeLabel': 'เวลา',
        'flex.nameLabel': 'ชื่อ',
        'flex.phoneLabel': 'เบอร์',
        'flex.noteLabel': 'หมายเหตุ'
    },
    en: {
        'step1.title': 'Select Service',
        'step1.button': 'Next',
        'step2.dateLabel': 'Select Date',
        'step2.timeLabel': 'Select Time',
        'step2.placeholder': 'No date selected',
        'step2.loading': 'Please wait...',
        'step2.error': 'Failed to load times',
        'step2.noTime': 'No available slots',
        'step2.back': 'Back',
        'step2.next': 'Next',
        'step3.title': 'Contact Information',
        'step3.namePlaceholder': 'Full Name',
        'step3.phonePlaceholder': 'Phone Number',
        'step3.notePlaceholder': 'Notes (optional)',
        'step3.back': 'Back',
        'step3.next': 'Next',
        'step4.title': 'Review Booking',
        'step4.serviceLabel': 'Service:',
        'step4.dateLabel': 'Date:',
        'step4.timeLabel': 'Time:',
        'step4.nameLabel': 'Name:',
        'step4.phoneLabel': 'Phone:',
        'step4.noteLabel': 'Note:',
        'step4.back': 'Back',
        'step4.confirm': 'Confirm Booking',
        'popup.close': 'Close',
        'popup.calendarError': 'Failed to load calendar.',
        'popup.serviceError': 'Failed to load services.',
        'popup.timeError': 'Failed to load available times.',
        'popup.serviceNeeded': 'Please select at least one service.',
        'popup.dateNeeded': 'Please select a date.',
        'popup.timeNeeded': 'Please select a time.',
        'popup.nameNeeded': 'Please enter your name.',
        'popup.phoneNeeded': 'Please enter your phone number.',
        'popup.phoneFormatError': 'Invalid phone number format.',
        'popup.submitError': 'Booking submission failed.',
        'popup.bookingSuccess': 'Booking successful!',
        'calendar.holiday': 'Holiday',
        'service.noService': 'No services found',
        'flex.header': 'Booking Confirmed',
        'flex.altText': 'Your booking details',
        'flex.serviceLabel': 'Service',
        'flex.dateLabel': 'Date',
        'flex.timeLabel': 'Time',
        'flex.nameLabel': 'Name',
        'flex.phoneLabel': 'Phone',
        'flex.noteLabel': 'Note'
    },
    my: {
        'step1.title': 'ဝန်ဆောင်မှုရွေးချယ်ပါ',
        'step1.button': 'ရှေ့သို့',
        'step2.dateLabel': 'နေ့ရက်ရွေးချယ်ပါ',
        'step2.timeLabel': 'အချိန်ရွေးချယ်ပါ',
        'step2.placeholder': 'နေ့ရက်မရွေးချယ်ရသေးပါ',
        'step2.loading': 'ခဏစောင့်ပေးပါ...',
        'step2.error': 'အချိန်တင်မရနိုင်ပါ',
        'step2.noTime': 'အချိန်မရှိပါ',
        'step2.back': 'နောက်သို့',
        'step2.next': 'ရှေ့သို့',
        'step3.title': 'ဆက်သွယ်ရန်အချက်အလက်',
        'step3.namePlaceholder': 'အမည်အပြည့်အစုံ',
        'step3.phonePlaceholder': 'ဖုန်းနံပါတ်',
        'step3.notePlaceholder': 'မှတ်ချက် (ရှိပါက)',
        'step3.back': 'နောက်သို့',
        'step3.next': 'ရှေ့သို့',
        'step4.title': 'အချက်အလက်ပြန်စစ်ပါ',
        'step4.serviceLabel': 'ဝန်ဆောင်မှု:',
        'step4.dateLabel': 'နေ့ရက်:',
        'step4.timeLabel': 'အချိန်:',
        'step4.nameLabel': 'အမည်:',
        'step4.phoneLabel': 'ဖုန်းနံပါတ်:',
        'step4.noteLabel': 'မှတ်ချက်:',
        'step4.back': 'နောက်သို့',
        'step4.confirm': 'အတည်ပြုရန်',
        'popup.close': 'ပိတ်မည်',
        'popup.calendarError': 'ပြက္ခဒိန်တင်မရနိုင်ပါ',
        'popup.serviceError': 'ဝန်ဆောင်မှုတင်မရနိုင်ပါ',
        'popup.timeError': 'ရရှိနိုင်သောအချိန်တင်မရနိုင်ပါ',
        'popup.serviceNeeded': 'အနည်းဆုံးဝန်ဆောင်မှုတစ်ခုရွေးချယ်ပါ',
        'popup.dateNeeded': 'နေ့ရက်ရွေးချယ်ပါ',
        'popup.timeNeeded': 'အချိန်ရွေးချယ်ပါ',
        'popup.nameNeeded': 'ကျေးဇူးပြု၍ သင့်အမည်ထည့်ပါ',
        'popup.phoneNeeded': 'ကျေးဇူးပြု၍ ဖုန်းနံပါတ်ထည့်ပါ',
        'popup.phoneFormatError': 'ဖုန်းနံပါတ်ပုံစံမမှန်ကန်ပါ',
        'popup.submitError': 'တင်ပြမှုမအောင်မြင်ပါ',
        'popup.bookingSuccess': 'ဘိုကင်အောင်မြင်ပါပြီ!',
        'calendar.holiday': 'အားလပ်ရက်',
        'service.noService': 'ဝန်ဆောင်မှုမရှိပါ',
        'flex.header': 'ဘိုကင်အတည်ပြုပြီးပါပြီ',
        'flex.altText': 'သင်၏ဘိုကင်အသေးစိတ်',
        'flex.serviceLabel': 'ဝန်ဆောင်မှု',
        'flex.dateLabel': 'နေ့ရက်',
        'flex.timeLabel': 'အချိန်',
        'flex.nameLabel': 'အမည်',
        'flex.phoneLabel': 'ဖုန်းနံပါတ်',
        'flex.noteLabel': 'မှတ်ချက်'
    }
};
